### ISSUE TITLE
Compilation Issue: class 'JavaScriptError' cannot inherit from another class other than 'NSObject'

### ISSUE THREAD

**Issue by racer1988** [apollographql/apollo-ios#2201]
ApolloCodegen/.build/checkouts/apollo-ios/Sources/ApolloCodegenLib/Frontend/JavaScriptBridge.swift:9:14: error: 'Sendable' class 'JavaScriptError' cannot inherit from another class other than 'NSObject'

**Comment by morgz** [comment]
Same issue - After updating to Xcode 13.3

**Comment by racer1988** [comment]
Sorry yes, this is due to 

Swift 5.4 after updating to Xcode 13.3

**Comment by TizianoCoroneo** [comment]
Should be already fixed in 0.51.0 with [this PR](https://github.com/apollographql/apollo-ios/issues/2146). What version are you using?

**Comment by morgz** [comment]
0.49 - I'll update and report back

**Comment by racer1988** [comment]
@TizianoCoroneo I missed the last release. will update and do the same

**Comment by morgz** [comment]
> Should be already fixed in 0.51.0 with https://github.com/apollographql/apollo-ios/issues/2146. What version are you using?

Fixed for me after updating to 0.51.0

**Comment by LawJolla** [comment]
I think this issue is back in 13.4

First, thanks for everyone's hard work on this great project.  I'm an experienced web/node/elixir developer in way over my head so please forgive my poor bug report.

Building with the following codegen...
![Image 2022-05-18 at 3 22 11 PM](https://user-images.githubusercontent.com/17485128/169165408-707924ff-b68f-4754-a704-f7f9fcbcd1e1.jpg)


I get...
![Image 2022-05-18 at 3 20 06 PM](https://user-images.githubusercontent.com/17485128/169165259-20b52092-894b-4fb7-b992-76cdd04a1ea0.jpg)

This is a project I haven't worked with since XCode 13.1.  Seemed to work ok then.
Any ideas?  Thank you!

**Comment by calvincestari** [comment]
I'm still on Xcode 13.3.1, I'll install 13.4 and give this a test.

**Comment by calvincestari** [comment]
I've installed 13.4 and apollo-ios builds without error for me. I suggest deleting all build folders and trying again. It's possible some interim build artifact is messing things up.

**Comment by calvincestari** [comment]
CircleCI doesn't yet have a [macOS image](https://circleci.com/docs/2.0/testing-ios/) with Xcode 13.4 but as soon as it's available I'll update our CI to use that image and latest Xcode too.

**Comment by LawJolla** [comment]
> I've installed 13.4 and apollo-ios builds without error for me. I suggest deleting all build folders and trying again. It's possible some interim build artifact is messing things up.

Fixed!

Thank you for your follow up and kind reply to a new Swift developer... I know about blowing up my node modules, but didn't know clearing the XCode build was a thing.  Issue solved!

**Comment by calvincestari** [comment]
No problem, glad you got it working. Good luck with your project!

**Comment by heliumdice** [comment]
Hi Team Apollo,

I hate to be the barer of bad news

I have just updated to Xcode 13.4.1 and I am now seeing this problem. 

- I have the latest version of Apollo installed using SPM (0.51.2)
- I have deleted my derived data folder 
- I have tried removing/re-adding Apollo SDK
- Cleaning build folders

All to no avail 

 Can anyone offer any suggestions on how to fix this? I'm loosing my mind
 
 Thanks

<img width="1499" alt="Screenshot 2022-06-17 at 17 27 06" src="https://user-images.githubusercontent.com/1543954/174338832-ff75ac13-d519-42c3-b238-36ba8407d6c4.png">

**Comment by heliumdice** [comment]
@calvincestari Thank you so much for your super speedy reply.

I have tried your recommendation. However I am still getting the same error. 

'Sendable' class 'JavaScriptError' cannot inherit from another class other than 'NSObject' 

Is there anything else you can recommend trying?

**Comment by calvincestari** [comment]
I wish I did have another recommendation @heliumdice, but I'm at a loss here, I'm sorry. There seems to be nothing consistent about this error and what resolves it.
