### ISSUE TITLE
Generated code for inline fragments doesn't compile

### ISSUE THREAD

**Issue by florianschulz** [apollographql/apollo-ios#2981]
### Summary

After updating from 1.0.5 to 1.1.2, the generated code for inline fragments doesn't compile anymore for me without manual changes. The code generated for conformance to the `InlineFragment` protocol appears to prepend the `RootEntityType` with `Query.` which causes the swift compiler to throw the error `Cannot find type 'Query' in scope`. If I remove `Query.` manually, the code compiles again.

I'm using ApolloCodegenLib to generate swift package manager modules.

### Version

1.1.2

### Steps to reproduce the behavior

Generating swift code using `moduleType: .swiftPackageManager` for this query:
```graphql
query HeroForEpisode($ep: Episode!) {
  hero(episode: $ep) {
    groups {
      name
      entries {
        ... on Droid {
          primaryFunction
        }
        ... on Human {
          height
        }
      }
    }
  }
}
```
will generate this swift code:
```swift
public struct AsDroid: MyGeneratedSwiftPackage.InlineFragment {
  ...
  public typealias RootEntityType = Query.Hero.Group.Entry
  ...
}
```
which doesn't compile because of the `Query.`.

**Comment by calvincestari** [comment]
Hi @florianschulz 👋🏻 - I cannot reproduce the build error on `1.0.5`, `1.1.2` or `main`. I'm not sure why the `Query` type is being referenced there. Can you share the full schema and configuration that you're using to generate the code please.

**Comment by florianschulz** [comment]
Hi @calvincestari, unfortunately I cannot share our entire schema, but I've attached a somewhat minimal schema.json that should suffice to reproduce the described issue. I've also attached a graphql file containing a query that fits the attached schema. (I had to suffix both files with .txt for uploading them here.)

This is the code that we use for code generation inside a swift executable/tool package:
```swift
import Foundation
import ApolloCodegenLib
import ArgumentParser

struct MyAPICodegen: ParsableCommand {
    @Option(name: .shortAndLong, help: "The path to the root directory of the project.")
    var projectRoot = "."

    func run() throws {
        let packageName = "MyAPIPackage"
        let packagePath = "\(projectRoot)/\(packageName)"
        let apolloCodegenConfiguration = ApolloCodegenConfiguration(
            schemaName: packageName,
            input: ApolloCodegenConfiguration.FileInput(
                schemaPath: "\(projectRoot)/demo_schema.json",
                operationSearchPaths: ["\(projectRoot)/demo_graphql_files/*.graphql"]
            ),
            output: ApolloCodegenConfiguration.FileOutput(
                schemaTypes: ApolloCodegenConfiguration.SchemaTypesFileOutput(
                    path: packagePath,
                    moduleType: .swiftPackageManager
                ),
                operationIdentifiersPath: "\(packagePath)/Sources/OperationIDs/operationIDs.json"
            ),
            options: ApolloCodegenConfiguration.OutputOptions(
                queryStringLiteralFormat: .multiline,
                deprecatedEnumCases: .exclude,
                schemaDocumentation: .include,
                apqs: .disabled,
                cocoapodsCompatibleImportStatements: false,
                warningsOnDeprecatedUsage: .include,
                conversionStrategies: ApolloCodegenConfiguration.ConversionStrategies(
                    enumCases: .camelCase
                ),
                pruneGeneratedFiles: true
            )
        )
        do {
            try ApolloCodegen.build(with: apolloCodegenConfiguration)
        } catch {
            Self.exit(withError: error)
        }
    }
}

MyAPICodegen.main()
```

[demo_schema.json.txt](https://github.com/apollographql/apollo-ios/files/11332823/demo_schema.json.txt)
[Hero.graphql.txt](https://github.com/apollographql/apollo-ios/files/11332861/Hero.graphql.txt)

**Comment by AnthonyMDev** [comment]
For some reason I thought I had already fixed this one, but yes, it definitely seems like a bug. `Query` needs to be replaced with `{OperationName}.Data` in this case. Adding it to the list of bug fixes to be made ASAP.

**Comment by calvincestari** [comment]
> Hi @calvincestari, unfortunately I cannot share our entire schema, but I've attached a somewhat minimal schema.json that should suffice to reproduce the described issue. I've also attached a graphql file containing a query that fits the attached schema. (I had to suffix both files with .txt for uploading them here.)

Ah, I misunderstood. The sample query in the issue description refers to the StarWarsAPI schema so I thought it was a version of that public schema you were using. I'll see if I can reproduce it with the supplied files - thanks.

**Comment by calvincestari** [comment]
@AnthonyMDev I've confirmed I can reproduce the bug with the supplied schema/operation files; should be easier to track down now.

**Comment by BobaFetters** [comment]
Testing this out using version `1.1.3` and it looks like it is working correctly, both lines 107 and 123 are giving me the following:

`public typealias RootEntityType = HeroForEpisodeQuery.Data.Hero.Group.Entry`

@florianschulz can you verify if you are still seeing this issue with when using version `1.1.3`

**Comment by calvincestari** [comment]
@florianschulz I've confirmed my reproduction case is resolved with the move to `1.1.3`. I'm going to close this issue but please let us know if that does not fix it for you and we can take another look.

**Comment by florianschulz** [comment]
@BobaFetters @calvincestari Can confirm it is working correctly with version `1.1.3`. Thank you!
