### ISSUE TITLE
Implicit self capture semantic error at compilation

### ISSUE THREAD

**Issue by Kireyin** [apollographql/apollo-ios#3441]
### Summary

When compiling and trying to publish against latest version of Apollo, the compiler (Xcode 14.1) raises the following issue

`Apollo/Sources/Apollo/ApolloStore.swift:208:22: error: reference to property 'cache' in closure requires explicit use of 'self' to make capture semantics explicit`

Implicit `self` capture in closure is a recent feature, not supported by all version of Xcode. Having implicit capture in you closure is a breaking change.

I added a comment on the incriminating commit here  to help you locate the error-> https://github.com/apollographql/apollo-ios/commit/7d0c7e9c70fa1cfeefa7196f14b2297eb97b448f#r146660778

### Version

1.15.0

### Steps to reproduce the behavior

Compile with Xcode 14.1

**Comment by AnthonyMDev** [comment]
Thanks for the heads up on this one. We'll get this fixed. @calvincestari We stopped running our CI tests on Xcode 14.1 recently due to some limitation there, right?

**Comment by calvincestari** [comment]
Hi @Kireyin - how/where are you distributing the apps built with Xcode 14.1?

The current minimum [Xcode version required to submit to the App Store](https://developer.apple.com/ios/submit/) is Xcode 15. I don't recall the specific behaviour of self capture in the version of Swift that ships with Xcode 15 but I think it's reasonable for us to support only the minimum version required for App Store submission.

@AnthonyMDev, I think our issues re. CI was for iOS versions which are no longer available. I'll have to check exactly what versions of Xcode we have available to us on CI, there might be some macOS issues there too though.

**Comment by Kireyin** [comment]
Hello @calvincestari , thanks for the quick response.

We only distribute SDKs and our CI was set up with Xcode 14.1 following Apple's communication about the minimum support last year (https://developer.apple.com/news/?id=jd9wcyov). It seems that we missed the April announcement about Xcode 15.

Sorry to have raised a false issue.
